### ISSUE TITLE
!lg * x=avg(unknown) causes barf

### ISSUE THREAD

**Issue by alexjurkiewicz** [crawl/sequell#47]
< chequers> !lg * x=unknown
    < Sequell> Unknown field: unknown
    < chequers> !lg * x=avg(unknown)
    < Sequell> Cannot apply to [unknown] (want [#<OpenStruct type=[#<Sql::Type:0x000000020ae900 @type_string="ETD", @raw_type="ETD", @type="ETD",
                 @category="ETD">], return=#<Sql::Type:0x000000020ae7c0 @type_string="*">>, #<OpenStruct type=[#<Sql::Type:0x000000020ae360 @type_string="I",
                 @raw_type="I", @type="I", @category="F">], return=#<Sql::Type:0x000000020ae220 @type_string="F">>])

**Comment by greensnark** [comment]
Fixed, now has a better error message.
