### ISSUE TITLE
Add new server cjr to Sequell

### ISSUE THREAD

**Issue by gammafunk** [crawl/sequell#56]
We're adding a new WebTiles server:

https://crawl.jorgrun.rocks:8081

Here are the base urls for the logfiles/milestones:

http://www.jorgrun.rocks/meta/

and for ttyrecs/rcfiles/morgues:

http://www.jorgrun.rocks/ttyrec/
http://www.jorgrun.rocks/rcfiles/
http://www.jorgrun.rocks/morgue/

**Comment by greensnark** [comment]
Added in d42267d6c4992dde2da51a05103082ec15ef00fb
