### ISSUE TITLE
Add 0.18 branches and 0.18 tournament to Sequell

### ISSUE THREAD

**Issue by gammafunk** [crawl/sequell#59]
The tournament is scheduled for [20:00 UTC Friday 6 May to 20:00 UTC Sunday 22 May](http://dobrazupa.org/tournament/0.18/).

The following servers have a 0.18 branch set up with their logfile/milestones and any rcfiles and ttyrecs available from the same base URLs as their other branches:

http://crawl.berotato.org/crawl/meta/0.18/
http://crawl.xtahua.com/crawl/meta/0.18/
https://crawl.jorgrun.rocks/meta/0.18/
http://underhound.eu:81/crawl/meta/0.18/
http://lazy-life.ddo.jp:8080/meta/0.18/
https://crawl.project357.org/dcss-logfiles-0.18 and https://crawl.project357.org/dcss-milestones-0.18
http://crawl.develz.org/allgames-0.18.txt and http://crawl.develz.org/milestones-0.18.txt

We're still waiting on getting CAO set up and we're waiting to hear from the CWZ admin. I'll update the issue when 0.18 is available for those two servers.

**Comment by greensnark** [comment]
Completed in 62414562e4aefa9d09798ccbe21173aaa0a70890
